on:
  push:
    branches:
      - 'main'

env:
  NODE_VERSION: '14'
  JAVA_VERSION: '11'

jobs:
  its-a-kind-of-magic:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
      
    - name: Build Frontend
      run: |
          npm --prefix frontend install
          npm --prefix frontend run build
          mkdir -p ./backend/src/main/resources/static/; mv ./frontend/build/* $_

    - name: Set up Java ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
      
    - name: Build Backend
      run: |
        mvn -B package --file ./backend/pom.xml
        mkdir package; mv ./backend/target/* $_
      
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package/*.jar
